export const MOCK_BOOTH_DATA = [
  // 5/26 (화) - 총 9개
  {
    boothName: '이은',
    boothImage: '',
    hostName: '이은',
    boothAllTable: 50,
    boothUsageTable: 44,
    location: '원흥관 4층 입구',
    dates: ['2026-05-26'],
  },
  {
    boothName: '산업시스템공학과(동국대)',
    boothImage: '',
    hostName: '산업시스템공학과(동국대)',
    boothAllTable: 50,
    boothUsageTable: 10,
    location: '원흥관 주차장',
    dates: ['2026-05-26'],
  },
  {
    boothName: '손짓사랑회',
    boothImage: '',
    hostName: '손짓사랑회',
    boothAllTable: 50,
    boothUsageTable: 40,
    location: '만해광장',
    dates: ['2026-05-26', '2026-05-27'],
  },
  {
    boothName: '그리고 그림',
    boothImage: '',
    hostName: '그리고 그림',
    boothAllTable: 50,
    boothUsageTable: 50,
    location: '만해광장',
    dates: ['2026-05-26'],
  },
  {
    boothName: '에너지신소재공학과',
    boothImage: '',
    hostName: '에너지신소재공학과',
    boothAllTable: 50,
    boothUsageTable: 27,
    location: '만해광장',
    dates: ['2026-05-26'],
  },
  {
    boothName: '화공생물공학과',
    boothImage: '',
    hostName: '화공생물공학과',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '만해광장',
    dates: ['2026-05-26'],
  },
  {
    boothName: '중어중문학과',
    boothImage: '',
    hostName: '중어중문학과',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '명진관(법학관 방면)',
    dates: ['2026-05-26'],
  },
  {
    boothName: '동국대학교 영어영문학부',
    boothImage: '',
    hostName: '동국대학교 영어영문학부',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '명진관(법학관 방면)',
    dates: ['2026-05-26'],
  },
  {
    boothName: '국제통상학과',
    boothImage: '',
    hostName: '국제통상학과',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '사과관 3층 앞',
    dates: ['2026-05-26', '2026-05-27'],
  },

  // 5/27 (수) - 총 8개
  {
    boothName: '글로벌무역학과',
    boothImage: '',
    hostName: '글로벌무역학과',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '카페ING',
    dates: ['2026-05-27'],
  },
  {
    boothName: '동국대학교 건축공학부',
    boothImage: '',
    hostName: '동국대학교 건축공학부',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '만해광장',
    dates: ['2026-05-27'],
  },
  {
    boothName: '멋쟁이사자처럼',
    boothImage: '',
    hostName: '멋쟁이사자처럼',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '만해광장',
    dates: ['2026-05-27'],
  },
  {
    boothName: 'FC 엘레펜테',
    boothImage: '',
    hostName: 'FC 엘레펜테',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '만해광장',
    dates: ['2026-05-27', '2026-05-28'],
  },
  {
    boothName: '사학과',
    boothImage: '',
    hostName: '사학과',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '명진관(법학관 방면)',
    dates: ['2026-05-27'],
  },
  {
    boothName: '사회복지학과',
    boothImage: '',
    hostName: '사회복지학과',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '경영관 앞',
    dates: ['2026-05-27', '2026-05-28'],
  },

  // 5/28 (목) - 총 8개
  {
    boothName: '미래융합대학',
    boothImage: '',
    hostName: '미래융합대학',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '카페ING',
    dates: ['2026-05-28'],
  },
  {
    boothName: '프론티어',
    boothImage: '',
    hostName: '프론티어',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '만해광장',
    dates: ['2026-05-28'],
  },
  {
    boothName: '바이오시스템대학',
    boothImage: '',
    hostName: '바이오시스템대학',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '다향관 앞',
    dates: ['2026-05-28'],
  },
  {
    boothName: '시스템반도체학부',
    boothImage: '',
    hostName: '시스템반도체학부',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '법학관(다향관 방면)',
    dates: ['2026-05-28'],
  },
  {
    boothName: '첨단융합대학',
    boothImage: '',
    hostName: '첨단융합대학',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '법학관(대운동장 방면)',
    dates: ['2026-05-28'],
  },
  {
    boothName: '사회복지상담학과',
    boothImage: '',
    hostName: '사회복지상담학과',
    boothAllTable: 50,
    boothUsageTable: 0,
    location: '사과대 주차장',
    dates: ['2026-05-28'],
  },
];
